### ISSUE TITLE
Links Broken at "Getting Started DevOps Links" 

### ISSUE THREAD

**Issue by chinziii** [Tikam02/DevOps-Guide#149]
The following links are broken..

3 . [DevOps Roadmap by kamranahmedse](https://github.com/kamranahmedse/developer-roadmap/blob/master/img/devops.png)

7 . [IBM Kubernetes Handson Labs](https://github.com/IBM/kube101/tree/master/workshop)

would you please be kind and update or remove these links?
 This should streamline the content.

**Comment by Tikam02** [comment]
sure, i'm on it

**Comment by ismaelpadilla** [comment]
#154 fixes the link to DevOps Roadmap by kamranahmedse
