### ISSUE TITLE
Add more information in Data Streaming section

### ISSUE THREAD

**Issue by KimtVak8143** [Tikam02/DevOps-Guide#172]
I would like to add more information in Data Streaming section.

**Comment by KimtVak8143** [comment]
@Tikam02 will this issue be considered for Hacktoberfest 2022?
Anyways, I'd be happy to contribute to this repo.

**Comment by Tikam02** [comment]
hi @KimtVak8143 Join our DevOps Community - https://discord.gg/rpETpUka
