### ISSUE TITLE
Copied content

### ISSUE THREAD

**Issue by bregman-arie** [Tikam02/DevOps-Guide#26]
Hi Tikam,

I see quite a lot of copied content. For example, interview questions I wrote here: https://github.com/bregman-arie/devops-interview-questions

But also entire articles like this one:
https://medium.com/cracking-the-data-science-interview/how-operating-systems-work-10-concepts-you-should-know-as-a-developer-8d63bb38331f

I think it's totally messed up that you present this as your work while a lot of different people worked a lot of time on creating this content.

Could you please remove any content you copied and next time ask people and companies if you can share their content with some attribution?

Thank you.

**Comment by Tikam02** [comment]
@bregman-arie sure I'm on it to remove and just give the original content credit.

**Comment by Tikam02** [comment]
@bregman-arie  I agree with and want to apologize.
Removed the contents and given credits and links of the author.
