### ISSUE TITLE
[broken link] OS/Linux Concepts & Notes

### ISSUE THREAD

**Issue by bregman-arie** [Tikam02/DevOps-Guide#4]
When clicking on "OS/Linux Concepts & Notes" I get 404 page not found

**Comment by Tikam02** [comment]
@bregman-arie  sorry for the error.
Actually recently I am collecting notes and resource and I will add ASAP or today.

@bregman-arie  if you want to add any DevOps resources or OS-networking notes etc. I'll be a great help.
