### ISSUE TITLE
Can you please remove the roadmap from the repository

### ISSUE THREAD

**Issue by kamranahmedse** [Tikam02/DevOps-Guide#5]
Hey Tikam, 

Thank you for the work that you have put into making this guide. 

I am the [author of the DevOps roadmap](https://github.com/kamranahmedse/developer-roadmap#devops-roadmap) that you have [added to the repository](https://github.com/Tikam02/DevOps-Guide/blob/master/img/devops.png). I understand that your intentions are to help the community but the license does not allow the use of the roadmap images in this manner – can you please remove it from the repository and link the [original resource](https://github.com/kamranahmedse/developer-roadmap) if you have to. 

Also, I continue to maintain and polish these roadmaps from time to time so it is better to have the link instead. Hope you understand.

Thank you.

**Comment by Tikam02** [comment]
sorry @kamranahmedse for the mistake, I have removed the image of the roadmap, and added the link, and also  thanks for the concern and review thanks, sir : )

**Comment by kamranahmedse** [comment]
Thank you 🙏
