### ISSUE TITLE
Add more contents

### ISSUE THREAD

**Issue by Tikam02** [Tikam02/DevOps-Guide#57]
## Add more contents on following topis:
 - Kubernetes Concepts in Feynman terms : https://github.com/Tikam02/DevOps-Guide/tree/master/Container-orchestration/kubernetes
- More on How  to do things : https://github.com/Tikam02/DevOps-Guide/tree/master/how-to
- Add contents in CI-CD : https://github.com/Tikam02/DevOps-Guide/tree/master/CI-CD
- Add contents to servers : https://github.com/Tikam02/DevOps-Guide/tree/master/Servers

**Comment by zahrafalah** [comment]
I am interested in this issue

**Comment by fedGL** [comment]
For CI/CD, are you looking to include explanations on what CI/CD is, how it works, definitions, etc?

**Comment by Tikam02** [comment]
@fedGL Yup more on CI/CD parts anything.

**Comment by priyanka001tech** [comment]
I'm interested...Please assign me.!
