### ISSUE TITLE
Cloud Providers

### ISSUE THREAD

**Issue by Tikam02** [Tikam02/DevOps-Guide#58]
## Add following Contents to Cloud Providers - https://github.com/Tikam02/DevOps-Guide/tree/master/Cloud_providers
- Add basic concepts of following providers: 
  - AWS
  - GCP
  - Azure
- Add tips &  tricks 
- Add commands

**Comment by SambhavBhurtel** [comment]
Hi @Tikam02. I have a basic understanding of Cloud Computing concepts and cloud providers namely Azure, AWS, DigitalOcean, and GCP. Can you assign me this task? I will contribute to the best of my ability.

**Comment by Gajesh2007** [comment]
Hi @Tikam02, I have expert knowledge of Cloud Computing[AWS, DigitalOcean, Azure, GCP], and DevOps. Can you assign me this task?

**Comment by Tikam02** [comment]
@Gajesh2007 can you write about AWS EKS and it's multi tenant clusters concepts and commands in Feynman concept.

**Comment by Gajesh2007** [comment]
Yes

**Comment by Tikam02** [comment]
cool

**Comment by Shaishav-Anand** [comment]
Hello @Tikam02 i want to contribute to it and i will give my best effort as per you want. 😃

**Comment by creativeyashi** [comment]
Hello @Tikam02 i want to contribute to it and i will give my best as i have knowledge of Cloud Computing.

**Comment by Tikam02** [comment]
@creativeyashi yeah, sure.

**Comment by Sakura74** [comment]
I can give basics about GCP so can you assign it to me

**Comment by Akshat977** [comment]
Hi @Tikam02  ,
This issue seems to be a good initiation of my journey towards contribution to FOSS projects.
Can you please assign this to me?

**Comment by sourav25998** [comment]
Hello @Tikam02 . I am starting my open source contribution journey. This seems to be a good project to try my hands on. Can you please assign it to me?

**Comment by Tikam02** [comment]
It is open to contribute in this repository. Please remember to push quality contents not quantity,

**Comment by xmayukx** [comment]
Hello, @Tikam02  I've pretty good knowledge about cloud computing could you assign me this issue?

**Comment by shakeybuoy** [comment]
Hello, @Tikam02  I was looking for repos for hactoberfest and came across this. 
Azure hasn't been updated, I can help with that.

**Comment by Tikam02** [comment]
It's open to all repo, please contribute your commits.

**Comment by developerSuranjan** [comment]
@Tikam02 I am an AWS S3 bucket expert. Please assign this to me

**Comment by akshayamadhuri** [comment]
hey
i would like to contribute to this

**Comment by obiwan04kanobi** [comment]
Hello @Tikam02, I possess a fundamental understanding of AWS, and I'm eager to participate. Would you assignee this task to me, please?

**Comment by syedasgarahmed** [comment]
I want to contribute.

**Comment by syedasgarahmed** [comment]
@Tikam02 @Tikam02 I have made 2 pull requests. 1 for Digitalocean and another for AWS. 
Please review and approve the merge request.
Thank you.

**Comment by Mohammad-Ghiyasuddin** [comment]
Assign this to me

**Comment by Tikam02** [comment]
Hi All, 

It's an open-source project, so please feel free to contribute valuable and hands-on learning experiences to this repository. I warmly welcome contributions from the open-source community, and anyone can participate.

**Comment by anushka9555** [comment]
Hi, I have a basic understanding of cloud computing services. Can you please assign this task to me? I will try my best to complete it.

**Comment by Raj100** [comment]
I will also add my cloud knowledge assign me

**Comment by ApoorvBrooklyn** [comment]
I have basic Understanding and Knowledge of Cloud and other related Services. Can You Assign me this issue?

**Comment by Vishal-K-988** [comment]
I created a pull request. Please look into that :)
