### ISSUE TITLE
All about servers

### ISSUE THREAD

**Issue by Tikam02** [Tikam02/DevOps-Guide#88]
## Add following contents about the servers: [Servers file location](https://github.com/Tikam02/DevOps-Guide/tree/master/Servers)
- [ ] What is server
- [ ] Different type of servers
- [ ] All about servers

**Comment by jenistenxavier** [comment]
@Tikam02 : I'm willing to contribute on this issue. please assign it to me.

**Comment by Tikam02** [comment]
@jenistenxavier looking forward to it with good contents 👍🏻

**Comment by jenistenxavier** [comment]
Thank you. 
Ref - https://github.com/Tikam02/DevOps-Guide/pull/97
