### ISSUE TITLE
Add how to do stuffs

### ISSUE THREAD

**Issue by Tikam02** [Tikam02/DevOps-Guide#89]
###  Add tutorials,tips and tricks how to do things of devops 

- How to install 
- how to make pipelines
- how to use git-actions
- how to write yaml files

And more how to do things

**Comment by meenasn** [comment]
hi @Tikam02 , does using any AWS services fall under this category, eg: lambda, s3 etc ?

**Comment by Tikam02** [comment]
@meenasn yes and obviously they are AWS services.
Soon I'll add aws services contents on respective directories.

**Comment by tiramisubliss** [comment]
Hi @Tikam02 I have added this PR about how to install helm https://github.com/Tikam02/DevOps-Guide/pull/106

Thank you in advance.

**Comment by ShvetaVasisht** [comment]
Hi,
Can I take up how to write yaml file

**Comment by Tikam02** [comment]
@ShvetaVasisht it's open for contribution, please take whatever you want and add anything more informative. 👍🏻

**Comment by ShvetaVasisht** [comment]
@Tikam02 Thanks. I will take up how to write yaml file.

**Comment by ShvetaVasisht** [comment]
@Tikam02  created pull request #126

**Comment by Tikam02** [comment]
> @Tikam02 created pull request #126

Done
